# Use postgres/example user/password credentials
version: "3.1"
services:
  db:
    image: postgres:11-alpine
    restart: always
    container_name: postgres-technique-test
    environment:
      POSTGRES_USER: arp
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

# volumen local
volumes:
  db:
    external: true
